Lesson 2 (Histogram + Skeleton + Flex Preview)
js-tasks-ru/htmlcss-20210513_s-poteryuha pull request #3
Opened 2021-05-27 12:57 UTC by hir0protagonist

2021-05-27 12:57 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-01 09:59 UTC, GSemikozov requested changes

2021-06-01 09:59 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    flex: auto;
здесь я бы советовал указать явно `flex-grow: 1` поскольку если наш компонент будет растягиваться по ширине родителя (например, контейнера), то важно чтобы и колонки пропорционально растягивались вместе со своей оберткой

2021-06-03 09:10 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-03 13:52 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-03 13:56 UTC, hir0protagonist commented on 04-lection2/01-histogram/histogram.css
> +    flex: auto;
исправлено

2021-06-03 13:57 UTC, GSemikozov approved these changes

2021-06-03 13:57 UTC, merged